### ISSUE TITLE
Overview section, documentation link directs back to the same page

### ISSUE THREAD

**Issue by RossCavanagh** [MicrosoftDocs/well-architected#105]
Under the Overview section (https://learn.microsoft.com/en-us/azure/well-architected/#overview), the documentation link (https://learn.microsoft.com/en-us/azure/architecture/framework/) takes you back to the main page (https://learn.microsoft.com/en-us/azure/well-architected/).

This doesn't appear to be the expected behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Version Independent ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Content: [Microsoft Azure Well-Architected Framework - Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/)
* Content Source: [well-architected/index.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/index.md)
* Service: **waf**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by PageWriter-MSFT** [comment]
Hi @RossCavanagh, 

WAF was refreshed recently, and this issue has been addressed. 

Please check out the latest content: https://learn.microsoft.com/en-us/azure/well-architected/
