### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gokseloral** [MicrosoftDocs/well-architected#112]
Below best practice looks like missing a link and have a syntax issue

Make logs and metrics available for [critical internal dependencies]#logs-for-internal-dependencies).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 587d9417-8ad8-d9b9-28b6-b092b8e4f794
* Version Independent ID: 587d9417-8ad8-d9b9-28b6-b092b8e4f794
* Content: [Health monitoring - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/devops/health-monitoring)
* Content Source: [well-architected/devops/health-monitoring.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/devops/health-monitoring.md)
* Service: **waf**
* Sub-service: **waf-pillar-excellence**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Thanks @gokseloral.  We've committed a change for this and it will be released with the next WAF publish.  That should be complete by next week Tuesday.
