### ISSUE TITLE
Inclusion of NAT Gateway pricing

### ISSUE THREAD

**Issue by aquibqureshi26** [MicrosoftDocs/well-architected#124]
**Azure NAT Gateway**
Azure NAT Gateway is charged at a fixed rate per deployment hour. There’s additional cost for the amount of data transferred.
NAT Gateway resource hours billing begins immediately upon deployment.

Data processing for NAT Gateway is charged per GB of data transferred through NAT Gateway. Data transfer charges for NAT gateway include both outbound and return traffic. Unsolicited inbound traffic does not pass through a NAT gateway by design.

For more information, see.
https://azure.microsoft.com/pricing/details/azure-nat-gateway/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44aa7eeb-71dd-b240-5240-04d34cef3044
* Version Independent ID: 44aa7eeb-71dd-b240-5240-04d34cef3044
* Content: [Networking resources provisioning - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/cost/provision-networking-services)
* Content Source: [well-architected/cost/provision-networking-services.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/cost/provision-networking-services.md)
* Service: **waf**
* Sub-service: **waf-pillar-optimization**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Thanks for your feedback @aquibqureshi26, this page is set for deprecation and will be removed in a few weeks.  As such, I'm going to close this issue.

#please-close
