### ISSUE TITLE
how to find the low-carb azure region

### ISSUE THREAD

**Issue by cpinotossi** [MicrosoftDocs/well-architected#129]
There is no guidance on how to spot out the low-carbon regions at azure.
Any hints would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f03c93e-3e1a-b0f1-b0e7-664b07ceb3c8
* Version Independent ID: 8f03c93e-3e1a-b0f1-b0e7-664b07ceb3c8
* Content: [Application platform considerations for sustainable workloads on Azure - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/sustainability/sustainability-application-platform#deploy-to-low-carbon-regions)
* Content Source: [well-architected/sustainability/sustainability-application-platform.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/sustainability/sustainability-application-platform.md)
* Service: **waf**
* Sub-service: **waf-workload-sustainability**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by PageWriter-MSFT** [comment]
Hi @cpinotossi, Thanks for the feedback. Please check out this article: https://learn.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard.

I hope that helps you get started.
