### ISSUE TITLE
built in policy implementation

### ISSUE THREAD

**Issue by tshah2808** [MicrosoftDocs/well-architected#13]
[Enter feedback here]
Just wanted to find out what is the process to implement the identified policies here. In case leading with ALZ there are set of policies identified as that you could choose. Is there a preference on deployment tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d00f3c7-0292-4966-f8eb-1faff48625c6
* Version Independent ID: 7d00f3c7-0292-4966-f8eb-1faff48625c6
* Content: [Azure Well-Architected Framework (WAF) review for Azure Service Fabric - Microsoft Azure Well-Architected Framework](https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/azure-service-fabric-well-architected-framework?branch=release-servicefabric-ga)
* Content Source: [well-architected/services/azure-service-fabric-well-architected-framework.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/azure-service-fabric-well-architected-framework.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @tomvcassidy
* Microsoft Alias: **tomcassidy**

**Comment by tomvcassidy** [comment]
Hi @tshah2808, I believe that the security policies are automatically handled if you are using managed clusters. I can check with the product team, and I can see how you implement them if you are using a standard cluster.

Is ALZ Azure Landing Zone? I'm not familiar with that. How are you using it?

As for deployment tool, ARM templates are the recommended pathway.

**Comment by jocontr** [comment]
Closing per @tomvcassidy reply is correct. If you have additional questions please feel free to open a new bug. Thank you.

**Comment by jocontr** [comment]
#please-close
