### ISSUE TITLE
"Use Webjobs" checklist item is missing a configuration recommendation.

### ISSUE THREAD

**Issue by adner** [MicrosoftDocs/well-architected#131]
The checklist contains the item "Use Webjobs", but the "Configuration recommendations" section is missing this item

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4b1013-1137-d8db-da28-4db0e1f52e53
* Version Independent ID: 3b4b1013-1137-d8db-da28-4db0e1f52e53
* Content: [Azure App Service and reliability - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/service-guides/azure-app-service/reliability)
* Content Source: [well-architected/service-guides/azure-app-service/reliability.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/service-guides/azure-app-service/reliability.md)
* Service: **waf**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback. We have opened internal ticket #183345 on our backlog to investigate this issue.
