### ISSUE TITLE
Threat detection - vague

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/well-architected#136]
Most of the sections provide explicit recommendations about things to do or don't do, but the Threat Detection does not. It just mentions things that could be done, it would be better if this section provided stronger recommendations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e932903-7f56-94e3-b8d8-d5d0591b67cd
* Version Independent ID: 7e932903-7f56-94e3-b8d8-d5d0591b67cd
* Content: [Recommendations for identity and access management - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/security/identity-access?utm_source=substack&utm_medium=email)
* Content Source: [well-architected/security/identity-access.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/identity-access.md)
* Service: **waf**
* Sub-service: **waf-pillar-security**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by skabou** [comment]
Thank you for your feedback. We have opened internal ticket #196679 on our backlog to investigate this issue.
