### ISSUE TITLE
Could be more structured and simplified for everyone

### ISSUE THREAD

**Issue by rufinjose** [MicrosoftDocs/well-architected#137]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8a6c9d-b1bb-8d38-e4d9-35843d9fe669
* Version Independent ID: 6a8a6c9d-b1bb-8d38-e4d9-35843d9fe669
* Content: [How to use the Azure Well-Architected Framework documentation - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/what-is-well-architected-framework)
* Content Source: [well-architected/what-is-well-architected-framework.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/what-is-well-architected-framework.md)
* Service: **waf**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by ckittel** [comment]
Thank you for your feedback.  Do you have any specific examples of something that is unstructured and complex that we could focus on simplifying for you?  If so, please open another issue with specificity.  We cannot act on general feedback like this within a GitHub issue unfortunately.
