### ISSUE TITLE
Misspelled tiers in postgresql.md on line 121 

### ISSUE THREAD

**Issue by dewa55** [MicrosoftDocs/well-architected#140]
Hello,

There is typo on the line 121 https://github.com/MicrosoftDocs/well-architected/blob/3102c80edc1fdefd8aa3ced1277860d973692f36/well-architected/service-guides/postgresql.md?plain=1#L121

it says tier.s and it should be tiers

Kind regards,
Vedran Devcic

**Comment by ckittel** [comment]
Thank you @dewa55 for pointing this out.  I've fixed the identified typo and it should be live within about two business days.
