### ISSUE TITLE
Confusion on Service vs. Regional Outage in FMA page

### ISSUE THREAD

**Issue by AndrewCi** [MicrosoftDocs/well-architected#149]
To whom it may concern -

I was reviewing the FMA documentation and there is an example table provided. One column is 'Risk' and another is 'Effect/Mitigation/Note'. I understand conceptually that a service outage is isolated to one specific service and a regional outage is a complete region failure; however, I don't understand why auto-failover / RTO and RPO is only mentioned under regional outage line items.

For example, looking at Azure SQL component line items below:

![image](https://github.com/MicrosoftDocs/well-architected/assets/10524644/67c2e311-6ef3-491a-87c6-1bff0f694d40)

Would you not also be able to mitigate a service outage with a failover? 

Appreciate any clarification here thank you!

Best,
Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2164370-947e-3546-9e0f-f40db66ddddb
* Version Independent ID: c2164370-947e-3546-9e0f-f40db66ddddb
* Content: [Failure mode analysis recommendations - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/reliability/failure-mode-analysis#example)
* Content Source: [well-architected/reliability/failure-mode-analysis.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/reliability/failure-mode-analysis.md)
* Service: **waf**
* Sub-service: **waf-pillar-reliability**
* GitHub Login: @claytonsiemens77
* Microsoft Alias: **csiemens**

**Comment by skabou** [comment]
Thank you for your feedback. We have opened internal ticket #206042 on our backlog to investigate this issue.
