### ISSUE TITLE
Wrong link in Well Architected- [Azure Virtual Desktop design areas]

### ISSUE THREAD

**Issue by febrocks-msft** [MicrosoftDocs/well-architected#151]
Wrong link for [Azure Virtual Desktop design areas](https://learn.microsoft.com/en-us/azure/well-architected/azure-vmware/design-principles) should be https://learn.microsoft.com/en-us/azure/well-architected/azure-virtual-desktop/design-principles

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6df67d09-b3e8-56e6-eb3a-945050a52d73
* Version Independent ID: 6df67d09-b3e8-56e6-eb3a-945050a52d73
* Content: [Azure Virtual Desktop assessment - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/azure-virtual-desktop/assessment)
* Content Source: [well-architected/azure-virtual-desktop/assessment.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/azure-virtual-desktop/assessment.md)
* Service: **waf**
* Sub-service: **waf-workload-avd**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by skabou** [comment]
@febrocks-msft Thank you for your feedback.  I have submitted a PR to correct the link.  It will go live in the next build.
