### ISSUE TITLE
Does Azure Firewall have "basic/premium" or "standard/premium" SKUs?

### ISSUE THREAD

**Issue by tigormanmsft** [MicrosoftDocs/well-architected#16]
In the first item of the tabled list [HERE](https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-firewall?branch=release-firewall-ga&source=docs#recommendations-2), "Basic" and "Premium" SKUs are mentioned under the "Recommendation" column, but "Standard" and "Premium" SKUs are described under the "Benefit" column.  Either "basic" or "standard" should be used uniformly to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543582ab-2230-4950-4818-91786b5a82e2
* Version Independent ID: 543582ab-2230-4950-4818-91786b5a82e2
* Content: [Microsoft Azure Well-Architected Framework review - Azure Firewall - Microsoft Azure Well-Architected Framework](https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-firewall?branch=release-firewall-ga&source=docs)
* Content Source: [well-architected/services/networking/azure-firewall.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/networking/azure-firewall.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by Zimmergren** [comment]
#please-close
Resolved with this commit: https://github.com/MicrosoftDocs/well-architected/commit/c13f2bb0a97d539b85edd1a3be5f9ce07c7a3caf
