### ISSUE TITLE
Follow recommendation with a helpful suggestion for generating traffic for testing?

### ISSUE THREAD

**Issue by tigormanmsft** [MicrosoftDocs/well-architected#17]
In the table under [Recommendations](https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-firewall?branch=release-firewall-ga#recommendations-4), the second "Recommend" item suggests "Create initial traffic that is not part of your load tests 20 minutes prior to the test", but the corresponding "Benefit" item does not suggest how to do this, such as a helpful "For more information, see XXX" link used in the prior table row.  Would it make sense to suggest a utility such as iPerf3 or traceroute or ping or something better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543582ab-2230-4950-4818-91786b5a82e2
* Version Independent ID: 543582ab-2230-4950-4818-91786b5a82e2
* Content: [Microsoft Azure Well-Architected Framework review - Azure Firewall - Microsoft Azure Well-Architected Framework](https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-firewall?branch=release-firewall-ga)
* Content Source: [well-architected/services/networking/azure-firewall.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/networking/azure-firewall.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by Zimmergren** [comment]
Thank you for reporting this. This has been addressed in the latest version of the article. 

#please-close
