### ISSUE TITLE
Use SSL/TLS everywhere

### ISSUE THREAD

**Issue by tlam9631** [MicrosoftDocs/well-architected#24]
Re: Best practice on: "Use SSL/TLS everywhere" - SSL has been considered vulnerable, even TLS v1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe63f190-8f75-1c95-f1a4-9c6847561f44
* Version Independent ID: fe63f190-8f75-1c95-f1a4-9c6847561f44
* Content: [Overview of the security pillar - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-us/azure/architecture/framework/security/overview)
* Content Source: [well-architected/security/overview.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/overview.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **robbymillsap**

**Comment by stephen-sumner** [comment]
@JanetCThomas - This is done. But I don't know how to close it.

**Comment by stephen-sumner** [comment]
This is the ADO item: https://dev.azure.com/ceapex/Content%20Planning/_workitems/edit/697075/

**Comment by stephen-sumner** [comment]
#please-close
