### ISSUE TITLE
Scale unit not defined on recommendations page

### ISSUE THREAD

**Issue by kw217** [MicrosoftDocs/well-architected#25]
This page uses the term "scale unit" (in the recommendations) without definition. I found it hard to understand with no context. Perhaps make the first occurrence of "scale unit" link to https://docs.microsoft.com/en-us/azure/architecture/framework/mission-critical/mission-critical-application-design#scale-unit-architecture ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a77e8fe7-68a1-a984-8843-1569d7843f4d
* Version Independent ID: a77e8fe7-68a1-a984-8843-1569d7843f4d
* Content: [Cross-cutting concerns of a mission-critical workload on Azure - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-gb/azure/architecture/framework/mission-critical/mission-critical-cross-cutting-issues)
* Content Source: [well-architected/mission-critical/mission-critical-cross-cutting-issues.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/mission-critical/mission-critical-cross-cutting-issues.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @CalCof
* Microsoft Alias: **calcof**

**Comment by CalCof** [comment]
Thanks Keith, we will incorporate your feedback and add a link.

**Comment by skabou** [comment]
It appears this has been addressed.  Please re-open with additional details if help is still needed.

**Comment by skabou** [comment]
#please-close
