### ISSUE TITLE
No what's new section

### ISSUE THREAD

**Issue by LANETLTD** [MicrosoftDocs/well-architected#26]
[Enter feedback here]
Hi it would be great if there was a Whats New Section like there is for the CAF. many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Version Independent ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Content: [Microsoft Azure Well-Architected Framework - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [well-architected/index.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **robbymillsap**

**Comment by ckittel** [comment]
@dominicallen for consideration in aligning WAF to use a process like AAC & CAF's "What's New"

**Comment by dominicallen** [comment]
Thank you for the feedback! We've added this suggestion to our backlog for review
