### ISSUE TITLE
Good idea - Well architected framework discussion

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/well-architected#27]
Including the well architected framework review in this section is helpful. It should be done like this for all of the different services. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543582ab-2230-4950-4818-91786b5a82e2
* Version Independent ID: 543582ab-2230-4950-4818-91786b5a82e2
* Content: [Azure Well-Architected Framework review - Azure Firewall - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-firewall?toc=%2Fazure%2Ffirewall%2Ftoc.json&bc=%2Fazure%2Ffirewall%2Fbreadcrumb%2Ftoc.json)
* Content Source: [well-architected/services/networking/azure-firewall.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/networking/azure-firewall.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by stephen-sumner** [comment]
@DeanGross - Thank you for the input! I'll pass the feedback on.  Have a good one!
