### ISSUE TITLE
Networking/App Delivery - Reliability and Operational Excellence pages are identical? 

### ISSUE THREAD

**Issue by MarcosMMartinez** [MicrosoftDocs/well-architected#28]
When comparing these two pages, they're basically identical:

- https://docs.microsoft.com/en-us/azure/architecture/framework/services/networking/application-delivery/operational-excellence 
- https://docs.microsoft.com/en-us/azure/architecture/framework/services/networking/application-delivery/reliability

![image](https://user-images.githubusercontent.com/29489962/174404645-edc568ab-1002-4a93-b48c-a6986cb19510.png)

I don't understand - what's the rationale here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a22a84c6-204e-93e8-d8f3-9909701b7b37
* Version Independent ID: a22a84c6-204e-93e8-d8f3-9909701b7b37
* Content: [Application Delivery (General) and operational excellence - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-us/azure/architecture/framework/services/networking/application-delivery/operational-excellence)
* Content Source: [well-architected/services/networking/application-delivery/operational-excellence.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/networking/application-delivery/operational-excellence.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-stacywray
* Microsoft Alias: **robbymillsap**

**Comment by PageWriter-MSFT** [comment]
Hi @MarcosMMartinez, 

Thanks for pointing this out. WAF was refreshed recently, and this issue has been addressed. 

Be sure check out the latest guidance.
