### ISSUE TITLE
SLA estimator

### ISSUE THREAD

**Issue by lanicolas** [MicrosoftDocs/well-architected#30]
The repo of the SLA estimator referenced in this doc would benefit from adding a few steps on how to set up the App for people not familiar with building React Apps, the links included are not really helpful as they are missing a lot of steps. 

I build the App but still the SLA estimator does not seem to work, the search functionality does not work and does not find any service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4222c0-d412-99e4-70b3-23fabffeb730
* Version Independent ID: df4222c0-d412-99e4-70b3-23fabffeb730
* Content: [Business Metrics - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/business-metrics)
* Content Source: [well-architected/resiliency/business-metrics.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/resiliency/business-metrics.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **robbymillsap**

**Comment by ckittel** [comment]
@hallihan FYI on this feedback

**Comment by ShannonLeavitt** [comment]
@lanicolas - I think this issue has been resolved in the [latest version of the article](https://learn.microsoft.com/en-us/azure/well-architected/reliability/metrics#composite-slas). I'll close this issue now, but please open a new issue if you think there's still room for improvement. Thanks for your feedback!
