### ISSUE TITLE
Restricting Storage account to Outbound IP addresses of App Service

### ISSUE THREAD

**Issue by nelroosevelt** [MicrosoftDocs/well-architected#39]
Hi team, 

For Azure App Services (PAAS resources that uses a load balancer) and restricted the default internet access to storage account, could you add "Do not use the public OUTBOUND IP addresses of the PAAS resources (for example: Azure App Services) when configuring your storage account firewall when the resources are in the same region."

https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-faqs?source=recommendations

How do connections to Azure Storage in the same region work?
Having outbound connectivity via the scenarios above isn't necessary to connect to storage in the same region as the VM. Use network security groups (NSGs) as explained above to prevent this behavior. For connectivity to storage in other regions, outbound connectivity is required. The source IP address in the storage diagnostic logs will be an internal provider address, and not the public IP address of your VM when connecting to storage from a VM in the same region. To restrict access to your storage account to VMs in one or more virtual network subnets in the same region, use [Virtual Network service endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview). Don't use your public IP address when configuring your storage account firewall. When service endpoints are configured, you'll see your virtual network private IP address in your storage diagnostic logs and not the internal provider address.

The solution is to configure VNet integration and configure the VNet in the storage firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51543d24-fcc3-3f16-dc5a-8b08b0d9030e
* Version Independent ID: 51543d24-fcc3-3f16-dc5a-8b08b0d9030e
* Content: [Storage Accounts and security - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-us/azure/architecture/framework/services/storage/storage-accounts/security)
* Content Source: [well-architected/services/storage/storage-accounts/security.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/storage/storage-accounts/security.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-stacywray
* Microsoft Alias: **robbymillsap**

**Comment by v-fearam** [comment]
Hi @nelroosevelt
 
Sorry for the delay. 

To use private storage account from an AppService you could:

1-  [Use AppService Vnet Integration](https://learn.microsoft.com/azure/app-service/overview-vnet-integration). It will allow you to send all the network traffic to a VNET that you control. You could define NSG and , for example, you will be able to decide if you are going to access the  internet or not. 
2-  [Restrict access from all networks in the storage account](https://learn.microsoft.com/azure/storage/common/storage-network-security) 
3- [Create a private endpoint on your vnet to allow private access to storage account service](https://learn.microsoft.com/azure/storage/common/storage-private-endpoints). It must include a Private DNS zone in your vnet: [Azure Private Endpoint DNS configuration](https://learn.microsoft.com/azure/private-link/private-endpoint-dns)

The application doesn’t need any change, it will use the fully qualified domain name (FQDN) of the connection string, which now is going to resolve to the private endpoint internal IP. 

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
