### ISSUE TITLE
No mention of testing tools [issue moved from AAC]

### ISSUE THREAD

**Issue by ckittel** [MicrosoftDocs/well-architected#45]
Relocating this feedback from MicrosoftDocs/architecture-center#2697 into the Azure Well-Architected Framework issue tracker for triage.

On 5-March, 2021, @jnimander opened an issue and said:

The title of the page is "Testing tools" but I see no mention of any testing tools on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a246c94e-285e-774d-5922-010dcf87785e
* Version Independent ID: a246c94e-285e-774d-5922-010dcf87785e
* Content: [Testing tools - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/scalability/test-tools)
* Content Source: [well-architected/scalability/test-tools.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/scalability/test-tools.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **robbymillsap**

**Comment by ckittel** [comment]
@nickwalkmsft - content signal for app dev content in WAF.

cc: @dominicallen

**Comment by craigcaseyMSFT** [comment]
Hi @ckittel  -  I am performing work per https://github.com/MicrosoftDocs/well-architected-pr/pull/680 and saw this issue. Wondering if this can be closed for two reasons:

- Title of article has been changed from "Testing Tools" to "Testing Strategies"
- There are a couple mentions of tools referenced in the article now, such as Azure Load Testing

Please let me know your thoughts and if there are still changes/updates required, I can make them in that above referenced PR. Thanks!

**Comment by ckittel** [comment]
Indeed, thanks for checking @craigcaseyMSFT 

#please-close
