### ISSUE TITLE
404 page not found - twice

### ISSUE THREAD

**Issue by jjpinto** [MicrosoftDocs/well-architected#46]
Azure Well-Architected Framework review - Azure Kubernetes Service (AKS)
Found 404 page not found happened on both highlighted links below.

For context, consider reviewing a reference architecture that reflects these considerations in its design. We recommend that you start with the [**baseline architecture for an Azure Kubernetes Service (AKS) cluster**] 
https://learn.microsoft.com/en-us/architecture/reference-architectures/containers/aks/secure-baseline-aks
and **[Microservices architecture on Azure Kubernetes Service]**.
https://learn.microsoft.com/en-us/architecture/reference-architectures/containers/aks-microservices/aks-microservices
 Also review the [AKS landing zone accelerator](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/aks/enterprise-scale-landing-zone), which provides an architectural approach and reference implementation to prepare landing zone subscriptions for a scalable Azure Kubernetes Service (AKS) cluster.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e1daa5f-056e-b3cb-5296-5dc70a836b60
* Version Independent ID: 6e1daa5f-056e-b3cb-5296-5dc70a836b60
* Content: [Azure Well-Architected Framework review for Azure Kubernetes Service (AKS) - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/services/compute/azure-kubernetes-service/azure-kubernetes-service?wt.mc_id=techcomm_wablog_blog_azuremktg)
* Content Source: [well-architected/services/compute/azure-kubernetes-service/azure-kubernetes-service.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/compute/azure-kubernetes-service/azure-kubernetes-service.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by MGoedtel** [comment]
@jjpinto - Thanks for bringing this to our attention. I confirmed the links are broken and I'll create a work item today to get this fixed before the end of the day.

**Comment by MGoedtel** [comment]
Created PR yesterday that corrects the broken links and verified they work. #please-close
