### ISSUE TITLE
Guidance on Bastion usage or alternatives

### ISSUE THREAD

**Issue by jamescrowley** [MicrosoftDocs/well-architected#50]
It would be great to see guidance on securely accessing virtual machines in a sustainable way, as we’ve struggled with this. 

We have a small number of virtual machines running on a schedule, that require remote access.

These are accessed via a bastion (which appeared to be the most ‘azure’ way of doing so securely) - however the bastion service currently cannot be enabled/disabled or set to run on a schedule, so either we have to manually automate destroying and re-creating the bastion on a schedule (very slow and at the time we investigated certain features could only be enabled in the portal after creation) or just accept that we leave it running 24/7.

Any suggestions would be welcome!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dded14f9-e1af-2de7-e727-c8a6855f3337
* Version Independent ID: dded14f9-e1af-2de7-e727-c8a6855f3337
* Content: [Security considerations for sustainable workloads on Azure - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/sustainability/sustainability-security)
* Content Source: [well-architected/sustainability/sustainability-security.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/sustainability/sustainability-security.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by Zimmergren** [comment]
Hi @jamescrowley, thank you for submitting this request.

We've introduced this discussion with the sustainability teams internally to iterate on. We will update the guidance if we find a good recommendation to put into the general WAF sustainability guidance. 

Meanwhile, here are some relevant information for this topic: 

- ALZ guidance for VM remote access: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-virtual-machine-remote-access

Reading the guidance, the following seems to be the preferred options:

- Use existing ExpressRoute or VPN connectivity
- A single Azure Bastion host can be deployed in the hub virtual network, which can provide connectivity to Azure VMs on spoke virtual networks via virtual network peering. This configuration reduces the number of Azure Bastion instances to manage in your environment.

Hopefully, that helps a bit even if the guidance isn't updated yet.
Thanks!

#please-close
