### ISSUE TITLE
duplication in health modeling page

### ISSUE THREAD

**Issue by dantelmomsft** [MicrosoftDocs/well-architected#52]
Quantify application states paragraph is mostly a duplication of previous one. The duplication starts with "The overall health state can be impacted....."

Application Logs paragraph also has several duplicated lines from previous sections. Specifically:

[Telemetry correlation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/correlation) should be used to ensure transactions can be mapped through the end-to-end application and critical system flows, as this is vital to root cause analysis (RCA) for failures. Platform level metrics and logs such as CPU percentage, network in/out, and disk operations/sec should be collected from the application to inform a health model and detect/predict issues. This can also help to distinguish between transient and non-transient faults.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abfd2aa6-3382-d630-b636-315671d3e10c
* Version Independent ID: abfd2aa6-3382-d630-b636-315671d3e10c
* Content: [Health modeling for reliability - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/resiliency/monitor-model)
* Content Source: [well-architected/resiliency/monitor-model.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/resiliency/monitor-model.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **robbymillsap**

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017697

**Comment by v-fearam** [comment]
#please-close
