### ISSUE TITLE
Next Steps should point to Encryption, not to the same page. 

### ISSUE THREAD

**Issue by lachaves** [MicrosoftDocs/well-architected#57]
The suggested Next Step is pointing to the same page you are already in. Following the ToC it should point to Encryption instead. 
![Screenshot 2022-12-06 180334](https://user-images.githubusercontent.com/32776049/206052507-0a530b4a-3346-4777-b27c-ba78b63c5568.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: baccedfe-c0c9-cfd4-0aa5-406deeae32f9
* Version Independent ID: baccedfe-c0c9-cfd4-0aa5-406deeae32f9
* Content: [Data protection in Azure - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-storage)
* Content Source: [well-architected/security/design-storage.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/design-storage.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Thank you for finding this and taking the time to let us know.  @avjolsakaj has provided a fix for this in #61.  This change will likely be live in about 48 hours after that merges.
