### ISSUE TITLE
Next step is wrong

### ISSUE THREAD

**Issue by avjolsakaj** [MicrosoftDocs/well-architected#58]
For the next step is specified "Identity and access management", but there are some other steps inside Governance before going to Identity and Access Management:
![image](https://user-images.githubusercontent.com/18752945/206670521-4a5a51c9-9681-4ac2-94de-ab4494dbb392.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7b0ad11-642f-2d96-3b97-a1e5f5d87962
* Version Independent ID: f7b0ad11-642f-2d96-3b97-a1e5f5d87962
* Content: [Governance, risk, and compliance - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-governance)
* Content Source: [well-architected/security/design-governance.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/design-governance.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
Hi @avjolsakaj,


Sorry for the delay. 

The "Next steps" link is pointed to the next checklist to provide a path for the reader to navigate across the different design areas.  The sub-topics in this design area are linked under the "In this section" heading:

https://learn.microsoft.com/azure/architecture/framework/security/design-governance#in-this-section

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
