### ISSUE TITLE
NSG on gateway subnet can be applied

### ISSUE THREAD

**Issue by kaveaa** [MicrosoftDocs/well-architected#60]
Hi, 
https://learn.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-application-gateway#policy-definitions
states that no NSG must be assigned to the gateway subnet. We are doing that and have no problems with the gateway.
Our NSG looks like this:
![image](https://user-images.githubusercontent.com/13419567/207328074-7df81526-c842-4f47-8401-cf0b6949679a.png)
I think this would be a better/safer solution than not applying an NSG at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4de8b9d0-0c23-c210-57d5-c5a569360553
* Version Independent ID: 4de8b9d0-0c23-c210-57d5-c5a569360553
* Content: [Microsoft Azure Well-Architected Framework review - Azure Application Gateway v2 - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/services/networking/azure-application-gateway)
* Content Source: [well-architected/services/networking/azure-application-gateway.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/networking/azure-application-gateway.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by ckittel** [comment]
Totally correct.  That policy is meant for `GatewaySubnet` that hosts VPN gateways.  I'll get a fix in for this shortly.  Thank you!

**Comment by ckittel** [comment]
This change has been merged and will be live within the next 30 hours or so.  Thanks again for spotting this.
