### ISSUE TITLE
Reliability Webpage has non-working links

### ISSUE THREAD

**Issue by amkingze** [MicrosoftDocs/well-architected#69]
Team:

I am looking for a resource to share with a customer on the reliability of Azure.  This webpage has multiple video links that are not working and would be a really poor resource to share in it's current state.  Can you please assist with this?  Please let me know if you have any questions.

https://learn.microsoft.com/en-us/azure/architecture/framework/#reliability

Thank you!

Amy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Version Independent ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Content: [Microsoft Azure Well-Architected Framework - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/framework/#reliability)
* Content Source: [well-architected/index.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Can you let us know which video links are not working?  All of the "inline" videos are working from my side -- but maybe it's not those but another set of links you're seeing.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/671075/213739029-31b0a5fc-ba7a-458d-9fd2-42659e50dfc6.png">

**Comment by amkingze** [comment]
Hi Chad and Team,

Thank you for reaching out – I submitted the request and checked it afterwards and was working.  I assumed that someone on your team had already addressed the issues.  😊

Sorry for any inconvenience.  I should have looked into a ‘cancel request’ type of option.

Thanks again!

Amy Kingzett
Digital Specialist – Azure
701-433-4324 | ***@***.******@***.***> | Book time with Amy Kingzett ***@***.***?anonymous&ep=pcard>
***@***.***

**Comment by ckittel** [comment]
Thanks for confirming.  Have a great weekend.

#please-close
