### ISSUE TITLE
Availability, Complexity, Performance percentage value question

### ISSUE THREAD

**Issue by HappyThursday** [MicrosoftDocs/well-architected#7]
What will be the complexity percentage value and performance percentage value when adding an alternative queue when SQL database fails?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4222c0-d412-99e4-70b3-23fabffeb730
* Version Independent ID: df4222c0-d412-99e4-70b3-23fabffeb730
* Content: [Business Metrics - Microsoft Azure Well-Architected Framework](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/business-metrics?ns-enrollment-type=Collection&ns-enrollment-id=1kn2s8xqp01rj4)
* Content Source: [well-architected/resiliency/business-metrics.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/resiliency/business-metrics.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **robbymillsap**

**Comment by RobBagby** [comment]
Can you please restate your question? It is unclear how to address this?

**Comment by RobBagby** [comment]
#please-close
