### ISSUE TITLE
Article incorrectly states ANF is 3rd-party storage

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/well-architected#70]
Hello Geert van Teylingen Product Manager for Azure NetApp Files here.

The article incorrectly states ANF is 3rd-party storage, and puts it in the same bucket as "Silk, Flashgrid Storage".
This is NOT correct. ANF is a Azure native 1st-party storage offering, same as Managed disk, Azure storage etc.
https://azure.microsoft.com/en-us/products/netapp/ 

Please correct this statement urgently, as this puts ANF is a disadvantaged position against true 3rd-party offerings.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 305252b4-fedb-94d6-c761-6853b84d7b34
* Version Independent ID: 305252b4-fedb-94d6-c761-6853b84d7b34
* Content: [Oracle workload cost optimization - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/oracle-iaas/cost-optimization#optimize-workload-storage)
* Content Source: [well-architected/oracle-iaas/cost-optimization.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/oracle-iaas/cost-optimization.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @ckittel
* Microsoft Alias: **kegorman**

**Comment by ckittel** [comment]
Thanks, we'll address right away today

**Comment by ckittel** [comment]
Thank you for identifying this so promptly, @gvanteylingen.  We have already made the update at MicrosoftDocs/well-architected-pr#501 and this will ship with today's release, which happens in about four hours from now.  If there are any other changes after this, please let me know on Teams and we can accommodate.

#please-close

**Comment by ckittel** [comment]
This change is now live.

**Comment by gvanteylingen** [comment]
Thanks for the fast turnaround! Appreciated.

With kind regards/Met vriendelijke groet,

***@***.***
Geert van Teylingen
Azure NetApp Files Group Product Manager
Mobile: +31646234500 – Email: ***@***.******@***.***> |  ***@***.******@***.***>

https://azure.microsoft.com/services/netapp/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fservices%2Fnetapp%2F&data=02%7C01%7Cb-gevant%40microsoft.com%7Cdc8b62206c2c43b4244008d850d64928%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637348228564525803&sdata=L8gK1JdEli7qXS4ykiX%2F2GKvHqIXM9K1ebDe8FsM%2Fd0%3D&reserved=0>
Azure NetApp Files documentation found here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fazure%2Fazure-netapp-files%2F&data=02%7C01%7Cb-gevant%40microsoft.com%7Cdc8b62206c2c43b4244008d850d64928%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637348228564525803&sdata=08XnNk9FfQSxIP2JN5Eh0Yh%2BFS09Wbu%2Bqfq6q%2F0vhIU%3D&reserved=0>
