### ISSUE TITLE
Video could not be loaded error

### ISSUE THREAD

**Issue by robm82** [MicrosoftDocs/well-architected#72]
These videos were working a few weeks ago, but for some reason today I am seeing the below error when tying to play any video within the well-architected framework documentation:

![image](https://user-images.githubusercontent.com/47445676/215809452-6977f736-fbba-4960-a389-a62dbc1f7914.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Version Independent ID: 953cd3b7-f664-44f5-04bb-046a0f1079fe
* Content: [Microsoft Azure Well-Architected Framework - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [well-architected/index.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by hallihan** [comment]
@robm82 it appears this may have just been a transient error, the videos seem to be working now.  If you are still having issues, feel free to comment with more details. #please-close
