### ISSUE TITLE
and what?

### ISSUE THREAD

**Issue by mucifous** [MicrosoftDocs/well-architected#76]
From this page:
"Microsoft Sentinel **and** is a native control" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acf8952b-4364-2428-68d7-ed4ce7229848
* Version Independent ID: acf8952b-4364-2428-68d7-ed4ce7229848
* Content: [Azure security monitoring tools - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/security/monitor-tools)
* Content Source: [well-architected/security/monitor-tools.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/monitor-tools.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by PageWriter-MSFT** [comment]
Thanks for the feedback. This has been fixed and should be live within 24 hours.
