### ISSUE TITLE
SQL code blocks should be Kusto

### ISSUE THREAD

**Issue by jfbilodeau** [MicrosoftDocs/well-architected#85]
Good day,

On both of the following pages, the code blocks are labelled as SQL but should be labelled as Kusto instead:
- https://learn.microsoft.com/en-us/azure/architecture/framework/services/messaging/service-bus/reliability
- https://learn.microsoft.com/en-us/azure/architecture/framework/services/messaging/service-bus/operational-excellence

The same mislabelling seems to be present on other pages as well.

Thanks,

J-F

<img width="551" alt="image" src="https://user-images.githubusercontent.com/5893654/228666831-9d5e3cce-1d45-4c95-a2ce-4272e104c56f.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9477e74e-71af-d289-ba1c-cced11c079b5
* Version Independent ID: 9477e74e-71af-d289-ba1c-cced11c079b5
* Content: [Service Bus and reliability - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/services/messaging/service-bus/reliability)
* Content Source: [well-architected/services/messaging/service-bus/reliability.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/services/messaging/service-bus/reliability.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by jfbilodeau** [comment]
Just curious. It's been three week. Any movement on this?

**Comment by v-fearam** [comment]
#please-close

**Comment by jfbilodeau** [comment]
The code blocks are still marked as SQL instead of KQL. Any reason for that?

**Comment by v-fearam** [comment]
Yes, because it takes some time to be available.

**Comment by jfbilodeau** [comment]
I checked this morning, and I see Kusto instead of SQL. Thanks for the fix!
