### ISSUE TITLE
Diagram too small

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/well-architected#86]
There is a really nice reference diagram on this page but it looks like it has been screenshotted from some other guidance. 
https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-segmentation#reference-model
Can you link to the source of this image so the deeper layers can be looked at in more detail

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab10e81c-fd24-6ba4-79cc-b0763cac66f2
* Version Independent ID: ab10e81c-fd24-6ba4-79cc-b0763cac66f2
* Content: [Segmentation strategies - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-segmentation)
* Content Source: [well-architected/security/design-segmentation.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/design-segmentation.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **martinek**

**Comment by thommck** [comment]
That version is bigger but it still doesn't show the detail of the bottom
row.
It looks like it's a nested image or part of a bigger PDF pack. There are
no references anywhere to where the diagram is sourced from for a reader to
look into at greater detail

Thanks,
Thom

**Comment by PageWriter-MSFT** [comment]
Hi @thommck 

Thanks for pointing this out. WAF was refreshed recently, and that page has been deprecated and replaced by https://learn.microsoft.com/en-us/azure/well-architected/security/segmentation. 

Be sure to check out the latest updates for WAF.
