### ISSUE TITLE
[Typo] Title and first paragraph 

### ISSUE THREAD

**Issue by carlosdoliveira** [MicrosoftDocs/well-architected#88]
The title says "Target and non-functional requirements". I believe it was missing a "Target functional and non-functional requirements".

Also the first paragraph has the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d394ee5b-3912-86ff-938e-98537ab1e4d9
* Version Independent ID: d394ee5b-3912-86ff-938e-98537ab1e4d9
* Content: [Target and non-functional requirements - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/resiliency/design-requirements)
* Content Source: [well-architected/resiliency/design-requirements.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/resiliency/design-requirements.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by jmart1428** [comment]
This issue has been resolved. 
https://github.com/MicrosoftDocs/well-architected-pr/pull/597

**Comment by jmart1428** [comment]
#please-close
