### ISSUE TITLE
Unhelpful/inaccurate link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/well-architected#91]
The link about security and compliance blueprints https://servicetrust.microsoft.com/ViewPage/SCCIntroPage points to information about o365 and not to anything about azure blueprints. Please update to provide the appropriate content

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8675a433-5c90-d9de-b450-80431411d66c
* Version Independent ID: 8675a433-5c90-d9de-b450-80431411d66c
* Content: [Azure landing zone integration - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-governance-landing-zone)
* Content Source: [well-architected/security/design-governance-landing-zone.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/design-governance-landing-zone.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
#please-close
