### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/well-architected#92]
Defender for Cloud is listed twice and there is not any description for either one. Please remove one and add the appropriate descriptive text. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8675a433-5c90-d9de-b450-80431411d66c
* Version Independent ID: 8675a433-5c90-d9de-b450-80431411d66c
* Content: [Azure landing zone integration - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-governance-landing-zone)
* Content Source: [well-architected/security/design-governance-landing-zone.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/security/design-governance-landing-zone.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
#please-close
